services:
  postgres:
    image: postgres:16

    container_name: solance-postgres

    environment:
      POSTGRES_USER: solance
      POSTGRES_PASSWORD: solance
      POSTGRES_DB: solance

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: